package com.emzaro.aaa

import java.io.File

/** Turns a natural-language request into a starter project locally. AI providers can replace the templates later. */
class AIProjectGenerator(private val engine: StudioEngine) {
    fun generate(prompt: String): File {
        val clean = prompt.trim().ifBlank { "New Android App" }
        val name = clean.split(" ").take(3).joinToString("-").replace(Regex("[^A-Za-z0-9_-]"), "").ifBlank { "AI-App" }
        val project = engine.createProject(name)
        val activity = """
            package com.example.generated

            import android.os.Bundle
            import androidx.activity.ComponentActivity
            import androidx.activity.compose.setContent
            import androidx.compose.material3.MaterialTheme
            import androidx.compose.material3.Text

            class MainActivity : ComponentActivity() {
                override fun onCreate(savedInstanceState: Bundle?) {
                    super.onCreate(savedInstanceState)
                    setContent { MaterialTheme { Text(\"Generated by AAA\") } }
                }
            }
        """.trimIndent()
        engine.saveFile(project, "README.md", "# $name\n\nGenerated by AAA Mobile Studio.\n\nPrompt: $clean\n")
        engine.saveFile(project, "app/src/main/java/com/example/generated/MainActivity.kt", activity)
        engine.saveFile(project, "AAA_PROMPT.txt", clean)
        return project
    }
}
